# Generated by Django 3.0.4 on 2020-03-23 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='backend.Category')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Plattform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('provider', models.CharField(max_length=200, verbose_name='Anbieter')),
                ('freeOfCharge', models.BooleanField(default=True)),
                ('availableLiveOnly', models.BooleanField(default=True)),
                ('link', models.URLField(max_length=250, verbose_name='Link')),
                ('description', models.CharField(max_length=400, verbose_name='Beschreibung')),
                ('image', models.URLField(blank=True, max_length=250, verbose_name='Bild')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Category')),
                ('tags', models.ManyToManyField(blank=True, to='backend.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('organizer', models.CharField(max_length=200, verbose_name='Organisator')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('freeOfCharge', models.BooleanField(default=True)),
                ('availableLiveOnly', models.BooleanField(default=True)),
                ('link', models.URLField(max_length=250, verbose_name='Link')),
                ('description', models.CharField(max_length=400, verbose_name='Beschreibung')),
                ('image', models.URLField(blank=True, max_length=250, verbose_name='Bild')),
                ('datePublished', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Category')),
                ('tags', models.ManyToManyField(blank=True, to='backend.Tag')),
            ],
        ),
    ]
