# Generated by Django 3.0.4 on 2020-03-24 15:12

import autoslug.fields
import backend.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='name')),
                ('icon', models.URLField(blank=True, max_length=250, null=True, verbose_name='Icon-Link')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('website', models.URLField(blank=True, max_length=250, null=True, verbose_name='Webseite')),
                ('description', models.CharField(blank=True, max_length=400, null=True, verbose_name='Beschreibung')),
                ('image', models.URLField(blank=True, max_length=250, null=True, verbose_name='Bild')),
                ('datePublished', backend.helpers.CustomDateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='name')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Category')),
            ],
            options={
                'verbose_name_plural': 'subcategories',
                'unique_together': {('slug', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Plattform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('freeOfCharge', models.BooleanField(default=True)),
                ('availableLiveOnly', models.BooleanField(default=True)),
                ('link', models.URLField(max_length=250, verbose_name='Link')),
                ('description', models.CharField(max_length=400, verbose_name='Beschreibung')),
                ('image', models.URLField(blank=True, max_length=250, verbose_name='Bild')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.SubCategory')),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Organizer')),
                ('tags', models.ManyToManyField(blank=True, null=True, to='backend.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='organizer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.SubCategory'),
        ),
        migrations.AddField(
            model_name='organizer',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='backend.Tag'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('freeOfCharge', models.BooleanField(default=True)),
                ('availableLiveOnly', models.BooleanField(default=True)),
                ('link', models.URLField(max_length=250, verbose_name='Link')),
                ('description', models.CharField(max_length=400, verbose_name='Beschreibung')),
                ('image', models.URLField(blank=True, max_length=250, verbose_name='Bild')),
                ('datePublished', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.SubCategory')),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Organizer')),
                ('tags', models.ManyToManyField(blank=True, null=True, to='backend.Tag')),
            ],
        ),
    ]
