# Generated by Django 3.0.4 on 2020-03-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_title',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_accessibility',
            field=models.CharField(choices=[('live', 'live only'), ('permanent', 'permanent')], max_length=25, verbose_name='Zugang'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_description',
            field=models.CharField(max_length=400, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_link',
            field=models.URLField(max_length=250, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_organizer',
            field=models.CharField(max_length=200, verbose_name='Organisator'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_title',
            field=models.CharField(max_length=200, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_title',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
    ]
