# Generated by Django 3.0.4 on 2020-03-22 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200322_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.URLField(blank=True, max_length=250, verbose_name='Bild'),
        ),
        migrations.CreateModel(
            name='Plattform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('provider', models.CharField(max_length=200, verbose_name='Anbieter')),
                ('freeOfCharge', models.BooleanField(default=True)),
                ('availableLiveOnly', models.BooleanField(default=True)),
                ('link', models.URLField(max_length=250, verbose_name='Link')),
                ('description', models.CharField(max_length=400, verbose_name='Beschreibung')),
                ('image', models.URLField(blank=True, max_length=250, verbose_name='Bild')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Category')),
                ('tags', models.ManyToManyField(blank=True, to='backend.Tag')),
            ],
        ),
    ]
