# Generated by Django 3.0.4 on 2020-04-04 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20200404_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='subCategory',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='subCategory',
        ),
        migrations.RemoveField(
            model_name='plattform',
            name='subCategory',
        ),
    ]
