# Generated by Django 3.0.4 on 2020-04-04 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20200404_1703'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
