# Generated by Django 3.0.4 on 2020-04-04 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_delete_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='plattform',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
