# Generated by Django 3.0.4 on 2020-04-04 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20200404_1709'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
