# Generated by Django 3.0.4 on 2020-04-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_auto_20200404_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=700, verbose_name='Beschreibung'),
        ),
    ]
