# Generated by Django 3.0.4 on 2020-04-06 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('backend', '0024_auto_20200406_0419'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plattform',
            new_name='Channel',
        ),
    ]
