# Generated by Django 3.0.4 on 2020-04-09 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_auto_20200406_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizer',
            old_name='website',
            new_name='link',
        ),
    ]
