# Generated by Django 3.0.4 on 2020-04-25 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_auto_20200426_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='member',
            field=models.ManyToManyField(blank=True, to='backend.Member'),
        ),
    ]
