# Generated by Django 3.0.4 on 2020-04-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_auto_20200426_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Untertitel'),
        ),
    ]
