# Generated by Django 3.0.4 on 2020-04-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_event_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='donationLink',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='weitere Infos (Link)'),
        ),
    ]
