# Generated by Django 3.0.4 on 2020-05-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_auto_20200429_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='donationLink',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='Spenden (Link)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='Bild (Link)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='link',
            field=models.URLField(max_length=250, verbose_name='StreamLink (Link)'),
        ),
    ]
