# Generated by Django 3.0.4 on 2020-05-06 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('backend', '0033_auto_20200506_0348'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Associate',
        ),
        migrations.AddField(
            model_name='event',
            name='infoLinkText',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Beschreibung Link (weitere Infos))'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ort'),
        ),
    ]
