# Generated by Django 3.0.4 on 2020-05-10 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_auto_20200506_0414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associate',
            name='category',
        ),
        migrations.RemoveField(
            model_name='associate',
            name='tags',
        ),
    ]
