# Generated by Django 3.0.4 on 2020-05-10 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_auto_20200510_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='category',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='tags',
        ),
    ]
