# Generated by Django 3.0.4 on 2020-05-10 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_auto_20200510_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='member',
            new_name='associates',
        ),
    ]
