# Generated by Django 3.0.4 on 2020-05-11 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_auto_20200510_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='location',
            new_name='city',
        ),
    ]
