# Generated by Django 3.0.4 on 2020-05-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_auto_20200511_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Titel'),
        ),
    ]
