# Generated by Django 3.0.4 on 2020-05-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0039_auto_20200514_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ort'),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Stadt'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=2000, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='event',
            name='infoLinkText',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Beschreibung Link (weitere Infos))'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='event',
            name='subtitle',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Untertitel'),
        ),
    ]
